### PR TITLE
adds ability for checkpoints to early-delete potential erroneous chec…

### PR DESCRIPTION
**Pull request by bppr**
…kins

### CODE REVIEW

**Comment by ometa** [comment]
Nothing like merging and deploying a new feature the night before the race.... 🐴  🚀

**Comment by bppr** [comment]
:sheep: :it:

**Comment by bppr** [comment]
> Nothing like merging and deploying a new feature the night before the race.... 🐴 🚀

A Chiditarod tradition

**Comment by ometa** [comment]
Amen.

**Comment by ometa** [comment]
:shopping_cart:

**Pull request merged**
