### PR TITLE
Adds select2 search & dropdown to the Checkpoint checkin field

### PR DESCRIPTION
**Pull request by ometa**
It makes it much more intuitive for a user to find the correct team during team checkin.
Also: display what checkpoint the user is logged into.

chiscore dropdown

### CODE REVIEW

**Comment by ometa** [comment]
@bppr @gmmowry

**Comment by ometa** [comment]
@bppr can you please help stub out the tests that should be written in the future to test this new functionality.  The backbone stuff is beyond what I can invest at this moment but I want to make sure we capture the tests we need.

**Comment by ometa** [comment]
Teams need this now, merging and filing an issue to add spec coverage.

**Comment by bppr** [comment]
in testing some kind of 3rd-party-ui-widget thing like this I'd probably just verify that the right class has been added to the element when it gets rendered server-side

**Comment by ometa** [comment]
How could we test that jQuery makes the call to select2?

**Comment by bppr** [comment]
First, I'd extract your initializer for select2 from `$(document).ready` to a function that can be invoked without page-load, just to make the test have fewer potential states. It might even go well in the `CheckinBoardView` file or even in the constructor for that class.

Then, in the test, you change the fixture (in the `setFixtures` in beforeEach) so that select2 can find the element you need -- adding a `select` element with a `team_checkin` id as exists in the ERB.

Then I'd just do a spy on the Select2 func:

```js
var select2Spy = spyOn($.fn, 'select2');
new CheckinBoardView();
// or new CheckinBoardView().initSelect() or whatever the function is
expect(select2Spy).toHaveBeenCalled();
// or alternatively
expect(select2Spy).toHaveBeenCalledWith(select2options);
```

**Pull request merged**
